apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: azurefunc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azurefunc
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
