apiVersion: v1
kind: Service
metadata:
  name: azurefunc
  labels:
    component: azurefunc
spec:
  ports:
    - port: 4000
      targetPort: 80
  selector:
    component: azurefunc
  type: "LoadBalancer"
